spring:
  datasource:
    # 生产环境使用内网 IP 进行连接，提高安全性和传输速度
    url: jdbc:mysql://172.17.62.67:3306/kuaiyu_travel?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    password: ${PROD_DB_PWD}
  data:
    redis:
      host: 172.17.62.67
      password: ${PROD_REDIS_PWD}
  rabbitmq:
    host: 39.108.95.154
    port: 5672
    username: ${PROD_MQ_USER}
    password: ${PROD_MQ_PWD}

  # 生产环境 AI 密钥从服务器环境变量读取 TODO 配置虚拟机环境
  ai:
    openai:
      api-key: ${PROD_AI_API_KEY}

aliyun:
  oss:
    # 生产环境 OSS 密钥从服务器环境变量读取
    access-key-id: ${ALIYUN_AK}
    access-key-secret: ${ALIYUN_SK}